### ISSUE TITLE
Évolution des seuils des grades

### ISSUE THREAD

**Issue by aw73** [rachelwe/Simulateur-ecoindex#3]
Bonjour
Les seuils des grades A - G ont évolué. Voici le référentiel de données :
https://github.com/cnumr/ecoindex_reference/blob/main/ecoindex_reference.json
Les seuils actuellement définis dans ce projet sont dépréciés.
Bonne journée

**Comment by rachelwe** [comment]
Bonjour,
Les seuils sont mis à jour, merci pour l'information :)
Bonne journée
